#!/bin/sh

set -e

dpkg-maintscript-helper dir_to_symlink \
	/usr/share/openstack-dashboard/static /var/lib/openstack-dashboard/static -- "$@"

if [ "$1" = "configure" ] ; then
	adduser --system \
		--home /var/lib/horizon \
		--quiet \
		--disabled-password \
		--group horizon

	mkdir -p /var/lib/openstack-dashboard/secret-key
	chown www-data:www-data /var/lib/openstack-dashboard/secret-key

	mkdir -p /etc/openstack-dashboard
	if ! [ -f /etc/openstack-dashboard/local_settings.py ] ; then
		cp /usr/share/openstack-dashboard/local_settings.py /etc/openstack-dashboard/local_settings.py
	fi

	# Compress the JS and CSS with python-compressor and python-lesscpy
	/usr/share/openstack-dashboard/manage.py collectstatic --clear --noinput
	/usr/share/openstack-dashboard/manage.py compress --force
	if [ -f /var/lib/openstack-dashboard/secret-key/.secret_key_store ]; then
		rm /var/lib/openstack-dashboard/secret-key/.secret_key_store
	fi
	chown -R www-data /var/lib/openstack-dashboard/secret-key /var/lib/openstack-dashboard/static
fi

if [ "$1" = "triggered" ] ; then
	/usr/share/openstack-dashboard/manage.py collectstatic --clear --noinput
	/usr/share/openstack-dashboard/manage.py compress --force
	if [ -f /var/lib/openstack-dashboard/secret-key/.secret_key_store ]; then
		rm /var/lib/openstack-dashboard/secret-key/.secret_key_store
	fi
	chown -R www-data /var/lib/openstack-dashboard/secret-key /var/lib/openstack-dashboard/static
fi

#DEBHELPER#

exit 0
